// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_table_names
CharacterVector get_table_names(std::string path);
RcppExport SEXP _rccess_get_table_names(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(get_table_names(path));
    return rcpp_result_gen;
END_RCPP
}
// get_table_schema
Rcpp::DataFrame get_table_schema(std::string path, std::string table_name);
RcppExport SEXP _rccess_get_table_schema(SEXP pathSEXP, SEXP table_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type table_name(table_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_table_schema(path, table_name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rccess_get_table_names", (DL_FUNC) &_rccess_get_table_names, 1},
    {"_rccess_get_table_schema", (DL_FUNC) &_rccess_get_table_schema, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rccess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
