# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_table_names <- function(path) {
    .Call(`_rccess_get_table_names`, path)
}

get_table_schema <- function(path, table_name) {
    .Call(`_rccess_get_table_schema`, path, table_name)
}

get_table <- function(path, table_name, n_max = -1L) {
    .Call(`_rccess_get_table`, path, table_name, n_max)
}

